backend:
  name: github
  repo: mhbitarafan/tinysports-gatsby
media_folder: static/assets
public_folder: assets
collections:
  - name: products
    label: Product
    folder: src/markdown-pages/products
    create: true
    fields:
      - { name: name, label: Title, widget: string }
      - { name: secondName, label: Title2, widget: string }
      - label: "attributes"
        name: "attributes"
        widget: "list"
        fields: 
          - {label: name, name: name, widget: select, options: ["تولید کننده", "کشور سازنده", "سرعت"]}
          - {label: options, name: options, widget: string}
          - {label: visible, name: visible, widget: boolean}
  - name: categories
    label: Category
    folder: src/markdown-pages/categories
    create: true
    identifier_field: slug
    fields:
      - {label: name, name: name, widget: string}
      - {label: parent, name: parent, widget: relation, collection: categories, searchFields: ["name"], valueField: "name", displayFields: ["name"], required: false}
      - {label: slug, name: slug, widget: string}
      - {label: description, name: description, widget: text, required: false}
      - {label: image, name: image, widget: image, required: false}